### ISSUE TITLE
Can't build from scratch

### ISSUE THREAD

**Issue by Limag** [inyokaproject/inyokaedit#97]
The **make install** command fails with a missing data directory:
```
install -m644 -D plugins/libuu_knowledgebox.so  /usr/local/lib/inyokaedit/plugins
install -m644 -D plugins/libuu_tabletemplate.so /usr/local/lib/inyokaedit/plugins
install -m755 -d /usr/local/share/inyokaedit/community
cp -rf community/ubuntuusers_de /usr/local/share/inyokaedit/community
cp: cannot stat 'community/ubuntuusers_de': No such file or directory
Makefile:70: recipe for target 'install-data-ubuntuusersde' failed
make: *** [install-data-ubuntuusersde] Error 1

```
Workaround was to fetch the **ubuntuusers_de** directory from inyokaedit-data-ubuntuusersde_0.20.0-1-ppa~201709101424~ubuntu17.10.1_amd64.deb

**Comment by ElTh0r0** [comment]
Hi, thanks for mentioning this issue. Root cause for this is, that all Inyoka "community" related files had been pushed into a separate branch, since InyokaEdit could be used (in theory) for any Inyoka-based community.
You don't need to fetch the community files from a .deb package (and they are **not 100% compatible** with the current application master branch). You can find them in this branch: https://github.com/inyokaproject/inyokaedit/tree/community
This branch has to be copied into InyokaEdit root folder to run **make install** successfully.

I'll mention it inside the Readme, so that it is more clear what is needed to build it. Or if you have a more elegant solution, I'm happy for any input :)

**Comment by Limag** [comment]
Maybe use a wget call while running make install?

**Comment by ElTh0r0** [comment]
Yes. I'm no configure/makefile expert, but currently I'm thinking of a solution, which checks, if any community files are existing. If not, the script should propose to download the community branch (maybe wget or git clone) or to proceed without installing community files.

- [x] Short-term solution: Adding a note inside the Readme.

- [x]  Long-term solution: Script needs above improvements - support welcome.

**Comment by ElTh0r0** [comment]
Hi @Limag 
please excuse the delayed answer. I added a check for the community files into the configure script and made the handling more configurable (even if not recommended, as an option it is possible to deploy InyokaEdit without any community files).
If you are still interested in this topic, feel free to test the solution.
